### ISSUE TITLE
Trying to use error template

### ISSUE THREAD

**Issue by j0k3r** [liip/LiipThemeBundle#146]
I wanted to add custom error page while using LiipThemeBundle but came across a strange behavior.

As far as I can read in the README, adding an error should as easy as creating this kind of file: `app/Resources/themes/phone/TwigBundle/Exception/error404.html.twig`.

I've defined one for each available theme and after hitting an obvious 404 in the prod env, I still got the default error page (I also tried `http://127.0.0.1:8000/app_dev.php/_error/404.html`, same result). I thought it was related to my project so I created a fresh Symfony 3.0.2 install and got the same error.

I'm using the default configuration:

```yml
liip_theme:
    themes: ['standardTheme', 'winter_theme', 'weekend']
    active_theme: 'standardTheme'
    path_patterns:
        app_resource:
            - %%app_path%%/themes/%%current_theme%%/%%template%%
            - %%app_path%%/themes/fallback_theme/%%template%%
            - %%app_path%%/views/%%template%%
        bundle_resource:
            - %%bundle_path%%/Resources/themes/%%current_theme%%_%%current_device%%/%%template%%
            - %%bundle_path%%/Resources/themes/%%current_theme%%/%%template%%
            - %%bundle_path%%/Resources/themes/fallback_theme/%%template%%
        bundle_resource_dir:
            - %%dir%%/themes/%%current_theme%%/%%bundle_name%%/%%template%%
            - %%dir%%/themes/fallback_theme/%%bundle_name%%/%%template%%
            - %%dir%%/%%bundle_name%%/%%override_path%%

```

I started to dig into `FileLocator` and var_dumped all `$checkPaths` I found and got this:

```
string 'views/@Twig/Exception/error404.html.twig' (length=40)
string '/private/tmp/liip_project/app/Resources/themes/standardTheme/@Twig/Exception/error404.html.twig' (length=95)
string '/private/tmp/liip_project/app/Resources/themes/fallback_theme/@Twig/Exception/error404.html.twig' (length=96)
string '/private/tmp/liip_project/app/Resources/views/@Twig/Exception/error404.html.twig' (length=80)
string '/private/tmp/liip_project/app/Resources/themes/standardTheme/@Twig/Exception/error404.html.twig' (length=95)
string '/private/tmp/liip_project/app/Resources/views/@Twig/Exception/error404.html.twig' (length=80)
```
_First line is the `$name` given to the `locate()` method._

As you can see, it seems it's trying to find a template inside a `@Twig` folder instead of `TwigBundle`. I didn't find something on Google (except https://github.com/liip/LiipThemeBundle/issues/38) so I guess I misconfigured something :confused: 
Cleared the cache doesn't help.

Do you have any idea?
