### ISSUE TITLE
assetic:dump does not scan all themes

### ISSUE THREAD

**Issue by pentatonicfunk** [liip/LiipThemeBundle#25]
so i have configured my config : 
liip_theme:
    themes: ['AAA', 'BBB']
    active_theme : 'BBB'

and i executed : 
./app/console cache:clear --env=local
./app/console assetic:dump --env=local

but the dump just scan for BBB theme dir only
And AAA not scanned

i want the theme is dynamic, so the assetic:dump must scan all themes dir

**Comment by DZunke** [comment]
after having this problem i found a workaround. i had to move my themes to the "views"-folder and changed the configuration to use these folders. now assetic is loading all theme-styles.

``` yaml
# src/Acme/LayoutBundle/Resources/views/themes/default/layout.html.twig
# src/Acme/LayoutBundle/Resources/views/themes/mobile/layout.html.twig
# src/Acme/LayoutBundle/Resources/views/themes/tablet/layout.html.twig

#
liip_theme:
    themes: ['default', 'tablet', 'mobile']
    active_theme: 'default'
    load_controllers: false
    path_patterns:
        app_resource:
            - %%app_path%%/views/themes/%%current_theme%%/%%template%%
            - %%app_path%%/views/%%template%%
        bundle_resource:
            - %%bundle_path%%/Resources/views/themes/%%current_theme%%/%%template%%
        bundle_resource_dir:
            - %%dir%%/views/themes/%%current_theme%%/%%bundle_name%%/%%template%%
            - %%dir%%/views/%%bundle_name%%/%%override_path%%
```

before these changes only the last theme "mobile" was rendered - the others were ignored.

**Comment by dantleech** [comment]
Created a PR which seems to fix this: https://github.com/liip/LiipThemeBundle/pull/118

**Comment by dbu** [comment]
#118 is merged. can we close this issue now?

**Comment by alexander-schranz** [comment]
I did test the `assetic:dump` on `master` branch and it seems not to be fixed, I quickly added two new themes with assets but only the active theme was generated also I needed to remove the cache manually(rm app/cache/*) with app/console cache:clear the active theme was not deleted from cache.

the config:

``` yml
liip_theme:
    themes: ["default", "testtheme", "testtheme2"]
    active_theme: "default"
    load_controllers: false
assetic:
    use_controller: false
```
