### ISSUE TITLE
Add possibility configure fallbacks/moving themes in other directory

### ISSUE THREAD

**Issue by Koc** [liip/LiipThemeBundle#28]
Subj, maybe using mustache, like

``` yml
liip_theme:
  fallbacks:
    - "{{ app_path }}/Resources/design/{{ active_theme }}/views/{{ override_path }}"
    # ...
    - "{{ bundle_path }}/Resources/views/{{ override_path }}"
```
