### ISSUE TITLE
autodetect

### ISSUE THREAD

**Issue by vazgen** [liip/LiipThemeBundle#43]
Hello, 
first of all thanks for this bundle.  
This is not an issue, this is a question.   I have read documentation and some part still unclear for me. How does auto-detect work?

I can change current theme in controller  by code:

```
$activeTheme = $this->container->get('liip_theme.active_theme');
$activeTheme->setName("phone");
```

but I would like to do in automatically. In case of configurations like this it does not work.

```
liip_theme:    
    autodetect_theme: true
```

or

```
liip_theme:
    themes: ['web', 'tablet', 'phone']
    active_theme: 'web'
    autodetect_theme: true
```

or 

```
liip_theme:
   themes: ['web', 'tablet', 'phone']
   active_theme: 'web'
   cookie:
        name: NameOfTheCookie
        lifetime: 31536000 # 1 year in seconds
        path: /
        domain: ~
       secure: false
       http_only: false
  autodetect_theme: true
```

So how to configure and user auto-detection?

I know I can change theme in controller by $activeTheme->setName("phone");, but how to know "phone" or "other"?

Thanks
