### ISSUE TITLE
Feature request - More information in a theme

### ISSUE THREAD

**Issue by trsteel88** [liip/LiipThemeBundle#68]
What are your thoughts on expanding on the theme config so that it has a full name.

eg:
```yaml
liip_theme:
    load_controllers: false
    themes:
        themeKey1:
            name: 'Full theme name'
        themeKey2:
            name: 'Full theme name 2'
```

This would then be useful for creating a Choices form type within the application where a user can choose the theme while displaying a full theme name.

Also, I think it would then be handy if there was the option to specify fallback themes inside a theme. This would then allow the following:

```yaml
liip_theme:
    load_controllers: false
    themes:
        themeKey1:
            name: 'Full theme name'
        themeKey1-mobile:
            name: 'Theme 1 - Mobile'
            fallback:
                - themeKey1
        themeKey2:
            name: 'Full theme name 2'
```

Let me know what you think. I could submit a PR for the full name functionality along with a choice form type if this is something you would allow?
